# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
   send_embed:
    runs-on: ubuntu-latest
    name: Send an embed to Discord

    steps:
     - name: Run the GitHub Actions Status Embed Action
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
         # Discord webhook
        webhook_id: '819064230480576573'
        webhook_token: '2tfHPfirNzuSxg816gBN82qKJF8hPIJB'

        # Optional arguments for PR-related events
        # Note: There's no harm in including these lines for non-PR
        # events, as non-existing paths in objects will evaluate to
        # `null` silently and the github status embed action will
        # treat them as absent.
        #pr_author_login: ${{ github.event.pull_request.user.login }}
        #pr_number: ${{ github.event.pull_request.number }}
        #pr_title: ${{ github.event.pull_request.title }}
        #pr_source: ${{ github.event.pull_request.head.label }}
